# Generated by Django 5.0.1 on 2024-01-16 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=255, null=True)),
                ('descendants', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('s', 'story'), ('c', 'comment')], default='story', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(unique=True)),
                ('by', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(default='comment', max_length=20)),
                ('time', models.DateTimeField()),
                ('parent_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.story')),
            ],
        ),
    ]
