# Generated by Django 4.2.7 on 2023-12-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.CharField(default='story', max_length=20),
        ),
    ]
