# Generated by Django 5.0.1 on 2024-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(choices=[('c', 'comment'), ('s', 'story')], default='story', max_length=20),
        ),
    ]
