# Generated by Django 4.2.7 on 2023-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_comment_type_story_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
