# Generated by Django 4.2.7 on 2023-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_story_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
