# Generated by Django 4.2.7 on 2023-12-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_story_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
