# Generated by Django 4.2.7 on 2023-12-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_story_fetched_alter_story_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='fetched',
        ),
    ]
